- config/karma.conf.js
- config/systemjs.config.js
- gulpfile.js
- karma.conf.js
- package.json
- src/app/app.component.spec.ts
- typings.json
> Karma tests

- src/app/home/directives/home-series.component.css
- src/app/home/directives/home-series.component.ts
- src/app/home/directives/home-story.component.ts
- src/app/home/home.component.css
- src/app/home/home.component.html
- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
- src/app/series/series.component.ts
Implements #27.
Also updated some component selectors to start with `publish-` ... so Atom will stop bugging me.
> Home page v4 filtering

- package.json
- src/app/core/auth/auth.component.spec.ts
- src/app/core/cms/hallink.spec.ts
- src/app/core/cms/halobservable.spec.ts
- src/app/core/cms/halremote.ts
- src/app/core/upload/mime-type.service.spec.ts
- src/app/core/upload/upload.service.spec.ts
- src/app/core/upload/upload.service.ts
- src/app/core/upload/uuid.spec.ts
- src/app/shared/form/button.component.spec.ts
- src/app/shared/hero/hero.component.spec.ts
- src/app/shared/hero/hero.component.ts
- src/app/shared/image/image-loader.component.spec.ts
Angular2 testing only recently became stable.  Backfilling component tests we missed out on amidst the release candidates.  Mostly concentrating on the core/shared modules, which are more stable than the other feature modules, at the moment.
> Backfill tests

- src/app/search/directives/search-series-form.component.ts
- src/app/search/directives/search-story-form.component.ts
Resolves issue #54 with a debounce so that the search is not performed until the user has finished typing
> debounce the search text

- src/app/search/directives/series-list.component.css
- src/app/search/directives/series-list.component.ts
- src/app/search/directives/story-list.component.css
- src/app/search/directives/story-list.component.ts
- src/app/search/search.component.html
- src/app/search/search.component.ts
#53 
- Loading status is now a single card with a loading spinner
- Search results are cleared when new search parameters are given
> Fix search loaders

- package.json
- src/app/search/directives/search-series-form.component.css
- src/app/search/directives/search-series-form.component.ts
- src/app/search/directives/search-story-form.component.css
- src/app/search/directives/search-story-form.component.ts
- src/app/search/search.component.ts
I don't particularly like any of our options right now, but this seems like it would give us the least amount of trouble in the meantime. If we can settle on this for an interim solution for #52 then I'll Icebox an issue for the select2 dropdown style. (The Angular2 story on Chosen is not any better, BTW.) I could potentially put the X button inside the select box with a negative margin if we think that would be better. I could also not disable the placeholder option and get rid of the X button. Let me know you opinions if you've got any.
> provide a means to clear search select filters

- src/app/shared/model/audio-version.model.spec.ts
- src/app/shared/model/audio-version.model.ts
- src/app/story/directives/podcast.component.css
- src/app/story/directives/podcast.component.ts
See #75.
Set to either "yes" or "clean", on AudioVersion.explicit
> Itunes explicit flag

- src/app/shared/image/image-upload.component.css
- src/app/shared/image/image-upload.component.spec.ts
- src/app/shared/image/image-upload.component.ts
- src/app/shared/image/upload/image-file.component.css
When an image is deleted (existing, not new images), show the orange "changed" outline around the image upload placeholder.
For #88.  (And requires #105 be merged first).
> Image deleted indicator

- package.json
- src/app/core/audio/player.service.ts
- src/app/core/auth/auth.component.ts
- src/app/core/modal/modal.component.ts
- src/app/login/login.component.ts
- src/app/shared/model/audio-file-template.model.ts
- src/app/shared/model/audio-version-template.model.ts
- src/app/shared/wysiwyg/prosemirror.d.ts
- src/app/shared/wysiwyg/prosemirror.markdown.editor.ts
- src/app/shared/wysiwyg/wysiwyg.component.ts
- src/app/story/directives/podcast.component.ts
- src/app/story/story.component.ts
> Lint-o-rama

- src/app/shared/wysiwyg/prosemirror.markdown.editor.spec.ts
- src/app/shared/wysiwyg/prosemirror.markdown.editor.ts
- src/app/shared/wysiwyg/wysiwig.component.spec.ts
- src/app/shared/wysiwyg/wysiwyg.component.ts
- src/app/story/directives/basic.component.css
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
This addresses bug #127 by adding change detection on the primitive string value as well as binding to model changed.
> Wysiwyg discard after save

- src/app/core/audio/index.ts
- src/app/core/audio/playback/aurora-playback.spec.ts
- src/app/core/audio/playback/aurora-playback.ts
- src/app/core/audio/playback/index.ts
- src/app/core/audio/playback/native-playback.spec.ts
- src/app/core/audio/playback/native-playback.ts
- src/app/core/audio/playback/playback.ts
- src/app/core/audio/player.service.spec.ts
- src/app/core/audio/player.service.ts
- src/app/core/audio/validation/aurora-validation.spec.ts
- src/app/core/audio/validation/aurora-validation.ts
- src/app/core/audio/validation/index.ts
- src/app/core/audio/validation/validation.ts
- src/app/core/index.ts
Support using native audio playback when possible.  Only fall back to Aurora when there's no other choice.
Fixes #102.
> Native audio playback

- src/app/shared/image/image-upload.component.ts
Use `accept="image/*"` to restrict selectable file types for image upload.
> Restrict selectable file types for image upload.

- src/app/home/directives/home-series.component.css
- src/app/home/directives/home-series.component.spec.ts
- src/app/home/directives/home-series.component.ts
- src/app/series/series.component.html
- src/app/series/series.component.spec.ts
- src/testing/stub.routerlink.directive.ts
#120 and #121 for missing/incorrect links to stories in a series
> add links to stories in a series

- src/app/upload/shared/audio-player.component.ts
- src/app/upload/shared/click.directive.ts
- src/app/upload/shared/index.ts
- src/app/upload/templated/templated-upload.component.ts
- src/app/upload/upload.component.ts
- src/app/upload/upload.module.ts
> Click anywhere to upload audio file

- src/app/story/directives/player.component.ts
Teeny tiny PR to correct the embeddable player staging host (#169)
> Use correct play staging link.

- src/app/core/header/header.component.css
- src/app/series/directives/file-template.component.ts
- src/app/series/directives/series-templates.component.css
- src/app/series/directives/series-templates.component.ts
See #161 and #162. Also put #178 in here too, though header elements still overlap below ~475px screen width (maybe at that point we should do a hamburger menu?).
> Clarify Series Audio Version Template page

- src/app/series/directives/series-podcast.component.html
- src/app/shared/model/distribution.model.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
> Allow user to set author email for series

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.spec.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/audio-version.model.ts
- src/app/shared/model/distribution.model.spec.ts
- src/app/shared/model/distribution.model.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/shared/model/series.model.ts
- src/app/story/directives/podcast.component.ts
implements #164 and #155
Known issue: #194
> default story explicit to series explicit

- env-example
- src/app/core/core.env.ts
- src/app/story/directives/player.component.ts
Use an environment variable for PLAY_HOST instead of putting that in the component; and update the auth host for staging. Finishes up #169.
> Use env var for play host

- src/app/story/directives/hero.component.ts
#216 Stories published @ now were saying "Will be published..."
Initially I tried getting current time in the getter, but that caused Expression changed after checked errors. It has to get updated for this to actually work right, so I'm updating it in the ngDoCheck (ngOnChanges wasn't being called when Publish is clicked.)
> fixes publishedAt tense for stories published at current time

- src/assets/styles/pikaday-custom.css
#214 border-radius: 0 like we _mean_ it
> datepicker buttons have 0 border-radius

- src/app/shared/image/image-upload.component.ts
> fixes series thumbnail image before profile image upload

- src/app/search/directives/story-card.component.css
- src/app/search/directives/story-card.component.ts
#232 removes audio file count. I kept the layout and a placeholder for the play count, which is what is actually supposed to go in this spot (when we have it available.)
> removes audio file count from story card

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/story.model.ts
- src/app/shared/wysiwyg/wysiwyg.component.css
- src/app/story/directives/basic.component.ts
- src/app/story/directives/podcast.component.html
> Improve hints and such

- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.spec.ts
- src/app/story/directives/podcast.component.ts
Clarifies hint about overriding episode GUID, emphasizes impact, and annoys on blur! #229
> Clarify GUID override

- src/app/core/modal/modal.component.css
- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
- src/app/series/series.routing.ts
- src/app/shared/model/series.model.ts
- src/app/story/story.component.ts
#253, #261, #268 which are all closely related, so one PR to force user to save or discard their changes to stories and series
> Unsaved changes forces save or discard

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/feeder-podcast.model.ts
#241 again! Previous solution was a little too quick on the draw.
> Improve magical addition of http:// to urls

- src/app/series/directives/series-podcast.component.html
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
> adds support for enclosure prefix

- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.ts
> guid goes in advanced settings

- src/app/shared/date/datepicker.component.ts
- src/app/shared/date/timepicker.component.css
- src/app/shared/date/timepicker.component.ts
- src/app/story/directives/basic.component.css
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
> releasedAt updates

- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.ts
> Story explicit not required

- src/app/story/directives/player.component.ts
> Use rss feed as player subscribe link

- src/app/series/directives/series-feed.component.css
- src/app/series/directives/series-feed.component.spec.ts
- src/app/series/directives/series-feed.component.ts
> episodes in series table presentation

- src/app/shared/model/series.model.ts
- src/app/shared/model/story.model.ts
> remove description minimum length validation

- src/app/shared/hero/hero.component.css
> fixes affixed hero toolbar overflow

- src/app/shared/date/timepicker.component.ts
missed a spot in the parsing when I added the timezone to those time strings
> fix bug where 12 or 12:30am becomes pm

- src/app/shared/image/image-upload.component.spec.ts
- src/app/shared/image/image-upload.component.ts
#210 
(If you have trouble logging in to your local instance with Safari, try logging into staging first.)
> fixes image uploader in Safari

- src/app/core/modal/modal.component.ts
- src/app/series/directives/file-template.component.spec.ts
- src/app/series/directives/file-template.component.ts
- src/app/series/directives/series-templates.component.spec.ts
- src/app/series/directives/series-templates.component.ts
- src/app/shared/form/advanced-confirm.directive.ts
- src/app/shared/form/fancy-duration.component.ts
#291 Other than length, I'm not entirely sure how all these changes affect the validity of existing stories. For example, if I remove a segment from the template, stories still have that segment. I probably need some guidance here on appropriate instruction for the user for what we are asking them to confirm.
> asks user to confirm template changes

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-templates.component.ts
> Shorten template hint, hide empty subcategories, mention podtrac/blubrry

- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.spec.ts
- src/app/story/directives/podcast.component.ts
> episode show podcast author and move explicit to top

- src/app/home/home.component.css
- src/app/home/home.component.html
- src/app/home/home.component.spec.ts
> Plus sign to create new series when no series

- src/app/shared/form/button.component.spec.ts
- src/app/shared/form/button.component.ts
> fix double clicks causing double submit

- package.json
- src/app/app.component.html
- src/app/core/core.module.ts
- src/app/core/index.ts
- src/app/core/toastr/index.ts
- src/app/core/toastr/toastr.component.css
- src/app/core/toastr/toastr.component.spec.ts
- src/app/core/toastr/toastr.component.ts
- src/app/core/toastr/toastr.service.spec.ts
- src/app/core/toastr/toastr.service.ts
- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
- src/app/story/directives/hero.component.spec.ts
- src/app/story/directives/hero.component.ts
- src/app/story/directives/status.component.spec.ts
- src/app/story/directives/status.component.ts
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
> pop up a toast message when series or episode is created, updated, or deleted

- src/app/core/cms/haldoc.spec.ts
- src/app/core/cms/haldoc.ts
to fix #349 nulling releasedAt
> clears haldoc fields before setting data to allow fields to be nulled

- src/app/shared/model/base.model.ts
- src/app/shared/model/feeder-episode.model.spec.ts
- src/app/shared/model/feeder-episode.model.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/shared/wysiwyg/wysiwyg.component.ts
- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.spec.ts
- src/testing/mock.cms.service.ts
#353
(Also made tiny adjustment to Mock CMS Service to get rid of linting error in test logs.)
> Episode Web Link

- src/app/shared/model/feeder-podcast.model.ts
> Require category & explicit for podcast

- src/app/series/directives/series-basic.component.html
- src/app/series/directives/series-basic.component.spec.ts
- src/app/series/directives/series-basic.component.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/series/directives/series-templates.component.ts
- src/app/shared/form/fancy-field.component.html
- src/app/shared/model/series.model.ts
> Allow users to change accounts for existing series

- src/app/series/directives/series-basic.component.html
- src/app/shared/image/image-upload.component.spec.ts
- src/app/shared/image/image-upload.component.ts
- src/app/story/directives/basic.component.ts
> requires series profile and story cover images to be square

- src/app/series/series.component.html
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
> rename podcast distribution tabs

- src/app/home/directives/home-series.component.ts
> Sort dashboard stories by pub date

- src/app/shared/wysiwyg/prosemirror.markdown.editor.spec.ts
- src/app/shared/wysiwyg/prosemirror.markdown.editor.ts
- src/app/shared/wysiwyg/wysiwyg.component.ts
Tries creating a new state on every change.  (Except value changes originating from the editor itself... those do not trigger anything).
Should fix some issues around discarding/saving and adding/removing images.
> Fix wysiwyg discard

- env-example
- lib/server.js
- lib/util.js
- newrelic.js
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/core/modal/modal.component.ts
- src/app/error/error.component.css
- src/app/error/error.component.ts
- src/app/error/error.service.ts
- src/app/error/index.ts
- src/assets/google-analytics.js
> Error reporting

- buildspec.yml
- env-example
- src/app/core/core.env.ts
> Init buildspec

- buildspec.yml
- docker-compose.yml
Push the image built by docker-compose to ECR.
> Better buildspec

- src/app/series/directives/series-podcast.component.css
- src/app/story/directives/player.component.css
- src/assets/styles/forms.css
> Add forms.css styling for disabled and readonly inputs and textareas

- .prxci
- Dockerfile
- bin/application
- docker-compose.yml
- env-example
> Init PRX ci

- src/app/shared/model/invalid/audio.invalid.spec.ts
- src/app/shared/model/invalid/audio.invalid.ts
- src/app/upload/shared/audio-duration.component.spec.ts
- src/app/upload/shared/audio-duration.component.ts
- src/app/upload/shared/audio-input.component.spec.ts
- src/app/upload/shared/audio-input.component.ts
Don't invalidate 0-duration audio.  Also rounds any ms duration > 0 up to 1sec.
> Allow blank audio

- src/app/core/cms/index.ts
- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/testing/mock.haldoc.ts
> handle 404s for series and story 

- src/app/series/directives/series-feed.component.css
- src/app/series/directives/series-feed.component.spec.ts
- src/app/series/directives/series-feed.component.ts
> Add link to create new episode from series episode list 

- package.json
- src/app/story/directives/metrics-downloads.component.ts
- yarn.lock
and with update to Styleguide will resolve the bug in #435
> uses the timeseries chart

- src/app/series/directives/series-basic.component.html
- src/app/shared/image/image-upload.component.css
- src/app/shared/image/image-upload.component.ts
- src/app/story/directives/basic.component.ts
#447 add max-size messaging + validations for series and story images.
> Validate max size for images

- src/app/shared/model/feeder-episode.model.ts
- src/app/story/directives/player.component.spec.ts
- src/app/story/directives/player.component.ts
> Preview unpublished dovetail audio

- src/app/story/directives/player.component.spec.ts
- src/app/story/directives/player.component.ts
#460 for the player dimensions. Figuring out what it wanted set up for a test was harder than fixing the problem, but I have been able to verify it does the thing. So there should be no need to pull down and run this PR.
> fixes player iframe dimensions to be width=650 height=200

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/series/series.module.ts
- src/app/shared/model/feeder-episode.model.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/shared/model/story.model.spec.ts
- src/app/shared/model/story.model.ts
- src/app/story/directives/basic.component.css
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.spec.ts
- src/app/story/directives/podcast.component.ts
> Add new Apple Podcasts tags

- src/app/series/directives/series-feed.component.css
- src/app/series/directives/series-feed.component.spec.ts
- src/app/series/directives/series-feed.component.ts
> Highlight invalid episodes on series feed page

- src/app/shared/model/story.model.spec.ts
- src/app/shared/model/story.model.ts
> Make new Story in a Series smarter about template selection

- src/app/home/directives/home-series.component.ts
- src/app/home/home.component.ts
- src/app/search/search.component.ts
- src/app/series/directives/series-feed.component.ts
- src/app/shared/model/series.model.ts
Use `?zoom=` to speed up dashboard, search, and series-episode-list.
> Use zoom param

- .prxci
- buildspec.yml
- docker-compose-ci.yml
CI v2 https://github.com/PRX/internal/issues/132
> adds buildspec.yml and docker-compose-ci.yml for ci-v2

- env-example
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
> Warn on canceling a future-published episode's release date

- package.json
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.routing.ts
- src/app/authorization/authorization.component.css
- src/app/authorization/authorization.component.ts
- src/app/authorization/index.ts
- yarn.lock
Adds a route for `/permission-denied` when the styleguide AuthService responds with an invalid_scope error.
> Permission denied route

- package.json
- yarn.lock
depends on https://github.com/PRX/styleguide.prx.org/pull/107
> Bump styleguide version to 0.40

- src/app/core/audio/validation/native-validation.ts
- src/app/shared/model/invalid/audio.invalid.spec.ts
- src/app/shared/model/invalid/audio.invalid.ts
there may be better ways to fix this
> allows native-validation "mpeg" through as an mp3

- package.json
- src/app/shared/model/story.model.spec.ts
- src/app/shared/model/story.model.ts
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
- src/app/story/story.module.ts
- yarn.lock
- adds _Ad-Free_ toggle to Categories field
- refactor story model to handle tags as array always
- remove test related to tags parsing
> Replace story Category text input w/ prx-tags

- src/app/core/core.env.ts
- src/app/shared/model/story.model.spec.ts
- src/app/shared/model/story.model.ts
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
Feedback on the label for this field is welcome. A bit tricky to communicate what it's for.
> Add production notes to stories

- package.json
- src/app/shared/shared.module.ts
- src/app/shared/sticky/sticky.directive.ts
- src/app/story/story.component.css
- src/app/story/story.component.ts
- src/assets/styles/sticky.css
- src/styles.css
- yarn.lock
Edit any episode and scroll page. Publish box and Delete button should stay in view.
> Add sticky positioning to story publish box

- src/app/shared/model/story.model.ts
> Limit clean title length

- src/app/series-import/series-import.component.html
- src/app/series/production-calendar/production-calendar.component.css
- src/app/series/production-calendar/production-calendar.component.ts
- src/app/series/series.component.html
Replaces hero header with new status bar on Series edit/create, Production Calendar, and Import Podcast screens.
> Replace hero headers with new status bar

- .gitignore
- package.json
- src/app/core/core.module.ts
- yarn.lock
A bump to the Styleguide version to address some lingering issues from the audio upload port.
> Styleguide audio segment bugs

- package.json
- yarn.lock
- updates styleguide to 2.18.2
- includes fix for status bar z-index
- includes fix for button invalid tip layout in status bar
> #682: Fix status bar z-index

- src/app/series/directives/series-feed.component.ts
Change the default ordering to `published_released_at`.
> Sort the list view by published_released_at

- package.json
- src/app/shared/model/distribution.model.spec.ts
- src/app/shared/model/feeder-episode.model.spec.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/story-distribution.model.spec.ts
- src/app/shared/model/story.model.spec.ts
- src/app/shared/model/story.model.ts
- src/app/story/directives/status.component.css
- src/app/story/directives/status.component.ts
- src/testing/index.ts
- yarn.lock
For #702.  This should merge/deploy concurrently with PRX/cms.prx.org#544
Needs PRX/styleguide.prx.org#213.
http://cav.is/NhQAd83.mp4
> No unpublish via released at

- src/app/shared/model/story.model.ts
> adds MIN validator to season and episode number

- src/app/shared/model/feeder-episode.model.ts
Fixes #734.
Null/blank actually isn't valid for this field.  And "full" is the default, so just start with that.
> Require itunes episode type

- env-example
- package.json
- src/app/core/core.env.spec.ts
- src/app/core/core.env.ts
- src/app/shared/image/image-upload.component.ts
- src/app/shared/image/upload/image-file.component.ts
- yarn.lock
Closes #730
Blocked by https://github.com/PRX/styleguide.prx.org/pull/221
Updates components that use Styleguide upload service to use an explicit S3 endpoint URL, and drops the unused bucket acceleration flag.
Also updates related environment variables to be reduce ambiguity.
> Update upload component configurations

- env-example
- package.json
- src/app/core/core.env.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/image/image-upload.component.ts
- src/app/shared/image/upload/image-file.component.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/story/directives/podcast.component.ts
- yarn.lock
Waiting on a new version of Styleguide
> Pass public access host to uploader

- package.json
- yarn.lock
> Update styleguide version

- src/app/series/series.component.html
- src/app/series/series.component.ts
> Show RSS tab

- src/app/series/directives/series-feeds.component.css
- src/app/series/directives/series-feeds.component.html
- src/app/series/directives/series-feeds.component.ts
- src/app/shared/model/feeder-feed.model.spec.ts
- src/app/shared/model/feeder-feed.model.ts
Fixes #757 
Adds 3 new fields to the Series -> RSS Feeds tab:
> Multi feed wrap
