- src/app/home/directives/home-series.component.ts
- src/app/shared/model/audio-file.model.ts
- src/app/shared/model/audio-version.model.spec.ts
- src/app/shared/model/audio-version.model.ts
- src/app/shared/model/base.model.spec.ts
- src/app/shared/model/base.model.ts
- src/app/shared/model/image.model.ts
- src/app/shared/model/uploadable.model.ts
Had some misc bugs around uploading:
- Unsaved uploads not persisted/restored correctly in localstorage
- Changed from an upload-uuid-array to a string, so the model can actually tell when it's changed
- Fixed a big bug in the base model, where localstorage was being written even if the field hadn't changed
- Make sure models have default values set in their `decode()` method, for any `SETABLE` fields
Most of these changes aren't very obvious unless you're debugging the specific UI issue they cause.
> Uploader bugs

- src/app/series/directives/file-template.component.css
- src/app/series/directives/file-template.component.spec.ts
- src/app/series/directives/file-template.component.ts
- src/app/series/directives/series-basic.component.ts
- src/app/series/directives/series-templates.component.css
- src/app/series/directives/series-templates.component.spec.ts
- src/app/series/directives/series-templates.component.ts
- src/app/series/series.routing.ts
- src/app/shared/form/fancy-field.component.css
- src/app/shared/form/fancy-field.component.html
- src/app/shared/form/fancy-field.component.spec.ts
- src/app/shared/form/fancy-field.component.ts
- src/app/shared/model/audio-file-template.model.ts
- src/app/shared/model/audio-version-template.model.ts
- src/app/shared/model/base.model.spec.ts
- src/app/shared/model/base.model.ts
- src/app/shared/model/index.ts
- src/app/shared/model/invalid/audio.invalid.spec.ts
- src/app/shared/model/invalid/audio.invalid.ts
- src/app/shared/model/invalid/index.ts
- src/app/shared/model/invalid/template.invalid.spec.ts
- src/app/shared/model/invalid/template.invalid.ts
- src/app/shared/model/series.model.ts
- src/assets/styles/forms.css
- src/assets/styles/layout.css
Ability to edit audio version/file templates on the series.
Makes no attempt to warn the user about the "bad things" that might happen if you change the templates for a series with existing stories.  We'll probably lock that down more at some point in the future - but this PR at least gets all the functionality in place.
> Edit audio templates

- src/app/series/directives/series-basic.component.ts
addresses #93 and #64. Title and teaser fields are now single line text inputs for both story and series.
> single line title and teaser fields

- src/app/app.component.ts
- src/app/core/auth/auth.component.spec.ts
- src/app/core/auth/auth.component.ts
- src/app/core/auth/auth.service.spec.ts
- src/app/core/auth/auth.service.ts
- src/app/core/cms/cms.service.ts
- src/app/core/cms/haldoc.spec.ts
- src/app/core/cms/halremote.cache.ts
- src/app/core/cms/halremote.spec.ts
- src/app/core/cms/halremote.ts
- src/app/home/home.component.ts
- src/app/search/search.component.ts
- src/app/series/series.component.ts
- src/app/story/story.component.ts
- src/testing/mock.cms.service.ts
See #85.
This requires PRX/cms.prx.org#190 and PRX/id.prx.org#34 to run CMS and ID locally.
> Recover from token expiration

- src/app/shared/image/image-upload.component.spec.ts
- src/app/shared/image/image-upload.component.ts
- src/app/shared/model/base.model.spec.ts
- src/app/shared/model/base.model.ts
It was a "Really Bad Idea of Ryan's" (™) to alter the `images` array during the call to `get noImages()`.  Because it occurs during change detection.  Which really shouldn't change things.  Sad.
And more generally, a call to `model.changed()` should return false if the model is deleted AND new.
> Image removal change detection

- src/app/upload/shared/audio-cancel.directive.spec.ts
- src/app/upload/shared/audio-cancel.directive.ts
See #97.
Not sure of the best wording here, so I made it up.
There are actually a couple different scenarios around deleting an audio file:
1. New unsaved audio - we really do need to prompt for this, as clicking the X will remove all traces forever.
2. Saved audio - also prompting for this, but not quite as catastrophic, since your deletion won't be sent to the server until you click "Save".  (And you can always "Discard" first).
3. In-progress upload - not prompting for this.  Just cancel the upload.
4. Failed upload - not prompting for this, as there's nothing to save.
> Prompt before deleting audio files

- src/app/core/cms/halremote.ts
Fixes #114.  CMS was returning 401s for POST requests to publish/unpublish a story.
Turns out this was the only POST request Publish makes that doesn't include any data in the body.  And I was using the incorrect `http.post` signature as a result.
TMI: Which resulted in a non-json content type, and the browser sending the wrong `access-control-request-headers` header, and CMS returning that it doesn't allow the `authorization` header in the OPTIONS request, and then the browser didn't send `authorization` header with the POST, and thus a 401!
> Fix 401s for publish/unpublish buttons

- package.json
- src/app/core/upload/upload.service.ts
Publish encounters 403s after uploading a file, canceling mid-upload, then uploading the same file again.  The file must be sufficiently large that Evaporate splits it into multiple parts.
It seems it was trying to reuse the old upload parts because the file was identical, even though the S3 upload path (which includes a Publish-generated UUID) was different.  Setting `onlyRetryForSameFileName = true` forced Evaporate to only reuse the parts if the entire S3 key matches.  (Which it won't because of the guid).
Also see the [Evaporate 1.x docs](https://github.com/TTLabs/EvaporateJS/tree/7e6e65ad49ba3260e841d3de86c2984bc52af9c3#api), and [this github issue](https://github.com/TTLabs/EvaporateJS/issues/210).
This does not change the intermittent GET 403s seen in the console, which seem to be …
> Fix evaporate 403s

- src/app/shared/wysiwyg/prompt.component.ts
- src/app/shared/wysiwyg/prosemirror.markdown.editor.ts
- src/app/shared/wysiwyg/wysiwyg.component.ts
> Fix wysiwyg Cancel add link expression changed error

- src/app/shared/model/audio-version-template.model.ts
- src/app/shared/model/audio-version.model.spec.ts
- src/app/shared/model/audio-version.model.ts
PRX/cms.prx.org#202 now embeds most resources as paged `prx:items` instead of a flat array.
The only impact on Publish is the `prx:audio-file-templates` resource.  There's already a HalDoc method to fetch items, so this just switches to using that.
> Fetch items instead of array for audio file templates

- karma.conf.js
- src/app/home/directives/home-series.component.ts
- src/app/home/directives/home-story.component.spec.ts
- src/app/home/directives/home-story.component.ts
- src/app/shared/model/audio-version.model.spec.ts
- src/app/shared/model/audio-version.model.ts
Fixes #90 dashboard draft info.
> fix missing draft info on dashboard

- src/app/home/directives/home-story.component.ts
If you remove the audio from a piece without saving, the error `Reduce of empty array with no initial value` is thrown from the story duration calculation on the dashboard. I created this bug last week with the changes to show draft info on the dashboard.
> fix error caused by story duration map reduce on empty array

- src/app/series/directives/series-podcast.component.html
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
By default, `author` will be set to account holder's name. This allows the user to override the author name that will be displayed with their podcast. (See #167)
> Allow user to override default author name for podcast

- src/app/series/directives/series-podcast.component.css
- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.spec.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/form/fancy-field.component.html
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
#163, #165, #170, #176 
The one thing not covered here is explaining to the user that the custom path is used in the URL instead of the podcast id. I'm just still not clear on if users understand what the podcast id # is and what this hint should actually say. I think putting it in the context of the url prefix and suffix does help though (and fixing that bug where it wasn't actually showing up when set until requested from the API again.)
> Podcast Distribution custom path

- src/app/shared/image/image-loader.component.spec.ts
- src/app/shared/model/base.model.spec.ts
- src/app/shared/model/base.model.ts
- src/app/shared/wysiwyg/wysiwig.component.spec.ts
- src/testing/mock.haldoc.ts
Use replay subjects to make a model's related arrays observable, so you can tell when they've loaded.  Also allows loading single relations, if you pass `loadRelated = false` in the constructor.
```
story.loadRelated().subscribe(() => ...);
story.loadRelated('versions').subscribe(() => ...);
story.loadRelated('versions', true).subscribe(() => ...);
```
Also allows force-setting a field, which will update the original value:
```
version.set('label', 'This will be original looking', true);
version.changed('label'); #false
```
> Explicitly observable related models

- src/app/series/directives/series-basic.component.css
- src/app/series/directives/series-feed.component.css
- src/app/series/directives/series-feed.component.spec.ts
- src/app/series/directives/series-feed.component.ts
- src/app/series/series.component.html
- src/app/series/series.component.spec.ts
- src/app/series/series.routing.ts
Added a tab on Series edit that shows the stories for a podcast in the order they'll show up in the feed (#124), and will sort based on public / to-be-public / private status.
> Show podcast feed story order

- src/app/series/directives/series-podcast.component.css
- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
Per slack discussions... a podcast's custom/vanity path is no longer writeable.  If we want/need to change them from the ID to something more human-readable, we'll do it manually.
Also nukes `previewUrl` which is no longer used.
> Read-only custom podcast path

- src/app/shared/model/story.model.ts
addresses #205 with a workaround. We may at some point decide to return a body with PUTs, at which time we'll want to remove this.
> updates publishedAt with releasedAt

- src/app/core/cms/halremote.ts
CMS and Feeder may now return 200 (and a response body) from a PUT request.
> Allow 200 from PUT

- src/app/shared/date/datepicker.component.css
- src/app/shared/date/datepicker.component.ts
If the user types into the input field (if you tab to it or select the text, you can type over it), the datepicker will highlight red if the date entered is invalid. If the date is valid, an event will be emitted to update the model. Uses moment parsing to determine date, so if month and day is typed, auto sets to current year, if just month, auto sets to the 1st of that month in the current year.
> support invalid on datepicker

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/form/advanced-confirm.directive.spec.ts
- src/app/shared/form/advanced-confirm.directive.ts
- src/app/shared/form/fancy-field.component.html
- src/app/shared/form/fancy-field.component.ts
- src/app/shared/form/index.ts
- src/app/shared/shared.module.ts
#256 and #240 
If the new feed url is changed to a value that passes validation on a not new podcast, the user will be prompted to confirm the change. If the user clicks Cancel, the change is reverted.
> advanced field confirmation for new feed url

- src/app/shared/model/story.model.ts
- src/app/story/directives/player.component.css
- src/app/story/directives/player.component.html
- src/app/story/directives/player.component.spec.ts
- src/app/story/directives/player.component.ts
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/testing/mock.haldoc.ts
Load embed player from different sources:
Note that any changes to CMS will take a few seconds to propagate to feeder.  So it's fairly easy to get a broken embed player, if say, you just clicked the Publish button.
There are a couple feeder issues that will make this look not-entirely convincing at the moment, including: PRX/feeder.prx.org#177 and PRX/feeder.prx.org#181.
> Use feeder for embed player

- src/app/shared/model/distribution.model.spec.ts
- src/app/shared/model/distribution.model.ts
- src/testing/mock.haldoc.ts
#239 To answer Genevieve's question, yes Homepage Link must be required because `<link>` is a required element for `<channel>` in the RSS feed. To ease the burden on users, when a new Podcast Distribution is created, the Homepage Link is defaulted to the series alternate link, which is a link to the series on beta. This default can be overridden by entering any valid URL.
> defaults podcast homepage link to beta url

- src/app/home/directives/home-series.component.ts
- src/app/home/directives/home-story.component.css
- src/app/home/directives/home-story.component.spec.ts
- src/app/home/directives/home-story.component.ts
- src/app/search/directives/story-card.component.css
- src/app/search/directives/story-card.component.ts
- src/app/shared/form/fancy-field.component.ts
- src/app/shared/hero/hero.component.css
- src/app/shared/image/image-upload.component.ts
- src/app/shared/model/base.model.spec.ts
- src/app/shared/model/base.model.ts
- src/app/shared/model/feeder-episode.model.spec.ts
- src/app/shared/model/feeder-episode.model.ts
- src/app/shared/model/invalid/audio.invalid.spec.ts
- src/app/shared/model/invalid/audio.invalid.ts
- src/app/shared/model/invalid/base.invalid.spec.ts
- src/app/shared/model/invalid/base.invalid.ts
- src/app/shared/model/invalid/template.invalid.spec.ts
- src/app/shared/model/invalid/template.invalid.ts
- src/app/shared/model/story.model.ts
- src/app/story/directives/basic.component.ts
- src/app/story/directives/hero.component.spec.ts
- src/app/story/directives/hero.component.ts
- src/app/upload/upload.component.ts
Loosens up story validations per #275.
- New or Unpublished stories can save with only a title.
- Other fields/files/etc aren't required.  But if you enter a non-blank thing, it's going to be validated
- Publish button is disabled until strict validations pass
- Published stories disable the save button until strict validations pass
Also cleaned up the dashboard/search cards a bit, to make them load less data.  And to standardize on what sort of statuses we display in them.
> Allow saving invalid unpublished stories

- src/app/series/directives/series-podcast.component.css
- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/story/directives/player.component.ts
Adds public feed URL to Feeder Podcast Model for #197, and makes player component use it if set. Reworks location + appearance of new feed url + PRX feed so they work more intuitively with the public feed URL field as well.
> Add public feed url to feeder podcast.

- src/app/series/series.component.ts
- src/app/story/story.component.ts
#279 Fixes deleting both episodes and series with unsaved related models. It used to be this bug was just on series, but it's on episodes now too. If you create an episode with just a title, then upload either an image or audio to it, do not Save, instead Delete the episode, you'll see an error because the related model isn't destroyed because it had changes pending. To address this issue, any changes on series or episodes are discarded before deletion.
> discard changes before delete

- src/app/search/directives/search-story-form.component.spec.ts
- src/app/search/directives/series-card.component.ts
- src/app/search/directives/story-card.component.css
- src/app/search/directives/story-card.component.ts
- src/app/search/search-story.model.ts
- src/app/search/search.component.ts
- src/app/shared/model/audio-file-template.model.ts
- src/app/shared/model/audio-file.model.ts
- src/app/shared/model/audio-version-template.model.ts
- src/app/shared/model/audio-version.model.ts
- src/app/shared/model/series.model.ts
- src/app/shared/model/story.model.ts
> Update Story Search options and appearance

- src/app/shared/form/fancy-duration.component.css
- src/app/shared/form/fancy-duration.component.ts
- src/app/shared/form/padzero.pipe.spec.ts
- src/app/shared/form/padzero.pipe.ts
- src/app/shared/model/audio-file-template.model.ts
- src/app/shared/model/audio-version-template.model.ts
- src/app/shared/model/invalid/template.invalid.spec.ts
- src/app/shared/model/invalid/template.invalid.ts
Fixes #298.
- Mixed results on how this works in the browser.  If you type fast enough, or repeat characters, change detection doesn't seem to get a chance to update the field.  Ah well.  Good enough!
> Better duration picker

- src/app/core/cms/haldoc.ts
- src/app/core/modal/modal.component.css
- src/app/series/series.component.html
- src/app/shared/form/button.component.css
- src/app/story/directives/hero.component.spec.ts
- src/app/story/directives/hero.component.ts
- src/app/story/directives/status.component.css
- src/app/story/directives/status.component.spec.ts
- src/app/story/directives/status.component.ts
- src/app/story/index.ts
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/app/story/story.routing.ts
> Story status box

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.spec.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/form/advanced-confirm.directive.spec.ts
- src/app/shared/form/advanced-confirm.directive.ts
- src/app/shared/form/fancy-field.component.html
- src/app/shared/model/distribution.model.ts
Fixes #227.
- If there's only 1 audio-version-template for the series, just default to that when creating the podcast
- If > 1, make them explicitly pick it
- Annoy-on-change for the dropdown
- Fix some linting with the advanced confirm directive (doesn't seem to like `@Input('name') differentName`)
> Podcast template picker updates

- src/app/series/series.component.css
- src/app/series/series.component.html
#195 
Somehow I keep making unpopular UI choices, so I went with the safe bet here and only changed the one thing that was requested. My other thoughts were as follows:
a list of links (workflow is often Create Series/Podcast/Whatever -> Add Episode, and I feel we should have a link for that)
since we don't like icons
I don't like that full sentence search link at the bottom of the page. Add episode isn't very useful hidden down there either.
> change episodes in series link style

- src/app/series/series.component.html
- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
- src/app/shared/form/button.component.ts
- src/app/story/directives/status.component.ts
#311 The confirmation modal was being reopened when the Enter button was hit because it still had focus, so this blurs the focus from the Delete button to prevent it from re-opening the modal while the series/story is being deleted
> don't reopen delete modal on Enter

- src/app/story/directives/hero.component.spec.ts
- src/app/story/directives/hero.component.ts
- src/app/story/directives/status.component.spec.ts
- src/app/story/directives/status.component.ts
- src/app/story/story.component.ts
#333: call a new episode "Draft" instead of "New" and make the button text "Save" instead of "Create" (note: for now, just doing this for episode since that's what we got feedback on. Can change for Series too to match if we like.)
#339: reinstate good old Delete button (outside of status box to keep that very clean -- but we can put in status box if we like)
> Call new episodes drafts, and reinstate Delete button

- src/app/app-error.service.ts
- src/app/core/modal/modal.component.css
- src/app/core/modal/modal.component.spec.ts
- src/app/core/modal/modal.component.ts
- src/app/core/modal/modal.service.spec.ts
- src/app/core/modal/modal.service.ts
- src/app/series/directives/file-template.component.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/series/directives/series-templates.component.ts
- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
- src/app/shared/form/advanced-confirm.directive.spec.ts
- src/app/shared/form/advanced-confirm.directive.ts
- src/app/story/directives/podcast.component.ts
- src/app/story/directives/status.component.spec.ts
- src/app/story/directives/status.component.ts
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/app/upload/shared/audio-cancel.directive.spec.ts
- src/app/upload/shared/audio-cancel.directive.ts
#325 "Discard Changes" doesn't feel right. It's too big, and all of our other buttons are a single verb.
> Unsaved changes primary button label changed to Discard

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- karma.conf.js
- lib/server.js
- lib/util.js
Fixes #26.
Finally found an alpine+phantom project that works.  And doesn't require building from source.  Not quite as slick as a selenium/webdriver solution, but after struggling with that for awhile, I gave up.
This will install dev/optional dependencies into the docker container.  Which results in a slightly larger image.  But much better than non-alpine builds, which were pushing 1GB.
> Get phantom working in alpine

- package.json
- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.spec.ts
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/form/fancy-field.component.css
- src/app/shared/form/fancy-field.component.html
- src/app/shared/form/fancy-field.component.spec.ts
- src/app/shared/form/fancy-field.component.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/typings.d.ts
Working on #317 
To the podcast info form:
To make this happen:
also fixes #343
> Add podcast fields

- src/app/core/audio/player.service.ts
- src/app/core/audio/validation/index.ts
- src/app/core/audio/validation/native-validation.ts
If Aurora validation is taking too long (it fails on mp3s with large id3 images) ... fallback to native <audio> to get the type/duration.
Not always accurate, and lacks bitrate/frequency, but should work for podcast mp3s.
> Fallback to native validation

- src/app/shared/model/base.model.ts
- src/app/shared/model/base.storage.spec.ts
- src/app/shared/model/base.storage.ts
See #408.
There are conditions where localStorage methods will throw errors.  Some mobile platforms, safari private browsing, localStorage full, some security settings, etc.  Catch any and all localStorage errors, and gracefully fall back to in-memory storage.
Shouldn't have too much of an impact on Publish when using in-memory.  Other than when you refresh the page, you lose local changes.
A bit tricky to test, since you can't even log into publish in private browsing mode.  (The security settings are a lot more strict).  But you can simulate by doing something like `localStorage.setItem = function() { throw new Error('bad'); }` in the console.
> Safe localstorage methods

- src/app/series/directives/series-podcast.component.css
- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
In the interest of soliciting feedback, here's one approach to #431: 
- allow edits to public feed URL
- show a checkbox users can check to set the new feed URL to this as well
- lots of messaging that if the feed is live and the public URL changes, the new feed URL should be set as well to redirect subscribers; plus lots of linking to Apple docs on how to handle source feed change.
> Editable public feed

- package.json
- src/polyfills.ts
- yarn.lock
resolves PhantomJS error `Can't find variable: Intl` by adding polyfill
> adds Intl polyfill

- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
Issues:
1. Delete an audio-file, then delete the audio-version, then save ... Publish fires off 2 DELETEs to CMS.  But CMS already destroys the child audio-files when the version is destroyed, so we end up getting a 404 for the 2nd DELETE.
2. Start with a saved story with 0 audio-versions.  When you go to add an audio-version from the dropdown, you get 2 (the 2nd that default "Main Audio").
Fixes:
> Audio version delete fixes

- src/app/upload/shared/audio.css
looks like this currently: 
not playing:
playing:
with this PR, will look like:
not playing:
playing:
> Small fixes of shared audio CSS 

- package.json
- yarn.lock
Doesn't actually solve #496, but at least fixes the URL-validations so you can't save your messed up URL.
Still has the issue where "strange things" can happen if you type in a leading space, or delete part of "http://".
> Upstream fix for url validator

- src/app/search/directives/search-series-form.component.ts
- src/app/search/directives/search-story-form.component.ts
- src/app/search/directives/series-card.component.ts
- src/app/search/directives/series-list.component.ts
- src/app/search/directives/story-card.component.ts
- src/app/search/directives/story-list.component.ts
- src/app/search/search.component.css
- src/app/search/search.component.html
- src/app/search/search.component.spec.ts
- src/app/search/search.component.ts
For #540 and #422.
Requires PRX/cms.prx.org#453.
> Use new CMS search endpoints

- src/app/series/directives/series-feed.component.css
- src/app/series/directives/series-feed.component.spec.ts
- src/app/series/directives/series-feed.component.ts
The easier fix for #550.
Still important that this page contain _all_ episodes/titles, for searchability.  But to avoid overwhelming CMS, load the episodes 50 at a time.
> Use some paging while loading full episode list

- src/app/series-import/series-import.component.spec.ts
- src/app/series-import/series-import.component.ts
- src/app/shared/model/series.model.spec.ts
- src/app/shared/model/series.model.ts
This PR prevents the podcast import component from creating an audio version template as part of creating the series.  The audio version templates will be created separately as part of the import process.
> Don't create version templates via publish when importing

- src/app/series-import-status-card/series-import-status-card.component.css
- src/app/series-import-status-card/series-import-status-card.component.html
A temporary fix until we can nail down some oscillations in CMS/Feeder and the Audio lambda. This PR prints out a simple warning (with a generous time window) to warn user about import lag time.
> warn import user

- package.json
- src/app/story/directives/basic.component.spec.ts
- src/app/story/directives/basic.component.ts
- yarn.lock
Rather than moving to a single select, which changes the underlying datatype to a `number` rather than an `number[]`, I've limited max selection to one. Since we're still planning to re-enable multiple templates in the future, it doesn't make sense to change the underlying Angular model.
> Limit max audio template selection to 1

- package.json
- src/app/story/directives/podcast.component.html
- yarn.lock
Marks `itunesType` as required and pulls in styleguide change which disables clearing selects when a field is marked as required.
> Episode type can't be blank

- src/app/story/directives/player.component.css
- src/app/story/directives/player.component.html
- src/app/story/directives/player.component.spec.ts
For #610.  Adds a copyable link to the dovetail mp3.
- Field only shows up for stories with a "podcast distribution"
- Will be blank until you upload at least 1 audio file
- Dovetail returns a 404 until you actually publish the story
> Episode mp3 link

- src/app/dashboard/dashboard-series.component.ts
- src/app/dashboard/dashboard-story.component.spec.ts
- src/app/dashboard/dashboard-story.component.ts
- src/app/dashboard/dashboard.component.ts
- src/app/shared/model/distribution.model.spec.ts
- src/app/shared/model/distribution.model.ts
- src/app/shared/model/story-distribution.model.spec.ts
- src/app/shared/model/story-distribution.model.ts
addresses #624 
I started to go the generic route with the guess id in the haldoc, but then I realized these actually weren't even hal links, they are url properties on a resource that we're treating like a link, and it was really looking like a static function in haldoc that didn't feel right, so I chose to go the specific route in the distribution models. Hopefully that's more of a guiding factor for future developers as well as guessing a link is not the recommended path (except in special cases I suppose.)
> improves performance by eliminating feeder requests for ids

- src/app/shared/model/feeder-episode.model.ts
- src/app/shared/model/series.model.spec.ts
- src/app/shared/model/series.model.ts
- src/app/story/directives/podcast.component.html
#598 Fixes series owner/accountId discard bug. The series owner field was not getting restored on discard because it's a sort of pseudo field that actually comes from the parent account.
#436 Also removes feeder episode url from required fields
> Fixes series owner discard

- src/app/shared/model/audio-version.model.spec.ts
- src/app/shared/model/audio-version.model.ts
For #643.  
If you somehow get > 1 audio_file with the same `position`, we were hiding the old ones.  Which would result in an error you can't fix.
This displays the extraneous files, at the bottom of the list.  (Meaning the oldest audio files with a duplicated `position` get this "Segment not in template" error message. 
Note there's another slight bug in how CMS [detects missing segments](https://github.com/PRX/cms.prx.org/blob/master/app/models/audio_version.rb#L80), which causes that 2nd "You must upload 2 segments (got 3)" error.  It doesn't handle > 1 file in the same position.
> Show extraneous audio files

- src/app/series/directives/series-podcast.component.css
- src/app/series/directives/series-podcast.component.html
Edit an Episode's Podcast Info. Ensure input elements and labels layout consistently in Chrome and Firefox. Wasn't able to test in Safari due to not being able to log into publish.prx.docker in Safari (weird?).
> Update layout of Publish Feed URL input elements

- src/app/series/directives/series-plan.component.html
- src/app/series/directives/series-plan.component.spec.ts
- src/app/series/directives/series-plan.component.ts
Allows users to set the publish time for planned episodes.
> Add timepicker to series planner

- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/story/directives/podcast.component.html
- src/app/story/directives/podcast.component.ts
Removes a broken link from the Series and Piece podcast tabs:
[This page](https://web.archive.org/web/20190505212417/https://support.apple.com/en-us/HT202005) in the apple docs apparently disappeared recently.  And I can't find anything similar in the Apple docs, so may as well remove it.  There is _some_ info under the [Content Requirements here](https://help.apple.com/itc/podcasts_connect/#/itc1723472cb) - which is where the 1st link in that sentence goes to.
If users end up needing more guidance, we'll probably have to create our own support page for this.
> Remove broken link

- src/app/story/directives/status-control.component.spec.ts
- src/app/story/directives/status-control.component.ts
For #704.  Turns out you could publish an episode with invalid audio (mismatching bitrates will do it ... but really any remote-detected audio error).
1) Create a new (or existing saved) episode.
2) Upload audio files _and_ set status dropdown to "Published" in a single step.  Click save.
3) Audio processes, completes and displays error message down in the "audio file uploader" box.
4) Publish POSTs to `/publish` the story, even though there were remote errors.
5) Feeder sees the `story.status` is invalid, but allows it through because of [this logic](https://github.com/PRX/feeder.prx.org/blob/master/app/jobs/story_update_job.rb#L17).  The bad audio could even end up in the public RSS feed!
> Prevent publishing remote audio errors

- src/app/series/directives/series-templates.component.css
- src/app/series/directives/series-templates.component.html
- src/app/series/directives/series-templates.component.ts
Adds a confirmation modal when you add a new audio template to a series with > 0 stories.
> Warn when adding audio templates to existing series

- src/app/story/directives/status-control.component.spec.ts
- src/app/story/directives/status-control.component.ts
Closes #698 (again).
Belt and suspenders - an upstream bug in HalRemote fixed some token retrying.  But just in case that doesn't fix it ... also break up the `togglePublish()` method.  So if there's a stray observable somewhere, it doesn't accidentally toggle-to-unpublished.
> Prevent accidental unpublish

- src/app/series/directives/series-podcast.component.css
- src/app/series/directives/series-podcast.component.html
- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
Closes #724.
Adds feeder episode limits to the Publish; on the Series -> Podcast info tab.  A bit down the form.
I opted to use plain text fields here, so you can easily clear them out.  And we validate whatever you enter is an integer > 0 or blank.
> Feeder episode limits

- src/app/search/search.component.ts
Gets up to 999 series in the Episodes Search Filter by Series dropdown. Fixes error on 'Search among these episodes.' link when series is not in the most recent 10.
closes #709
> fixes error on 'Search among these episodes.'

- src/app/series/directives/series-podcast.component.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/story/directives/podcast.component.ts
Deploy along with Feeder/CMS changes.
Use newest "true/false" strings for itunes:explicit.  But keeps displaying them as "Explicit" vs "Clean".
> Audio version explicit

- package.json
- src/app/series/directives/series-feeds.component.css
- src/app/series/directives/series-feeds.component.html
- src/app/series/directives/series-feeds.component.spec.ts
- src/app/series/directives/series-feeds.component.ts
- src/app/series/directives/series-podcast.component.html
- src/app/series/series.component.html
- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
- src/app/series/series.routing.ts
- src/app/shared/model/feeder-feed.model.spec.ts
- src/app/shared/model/feeder-feed.model.ts
- src/app/shared/model/feeder-podcast.model.spec.ts
- src/app/shared/model/feeder-podcast.model.ts
- src/app/shared/model/index.ts
- yarn.lock
Fixes #755.
Tackles a good chunk of the design in #748:
> Multiple feeds

- README.md
- src/app/series/directives/series-feeds.component.css
- src/app/series/directives/series-feeds.component.html
- src/app/series/series.component.css
- src/app/shared/model/feeder-feed.model.spec.ts
- src/app/shared/model/feeder-feed.model.ts
Finishing PRX/feeder.prx.org#436. Also fixed #762 with some minimal CSS.
The fields remain on their existing tabs for the default feed (`subtitle` and `description` are on "Basic Info", and `summary` is on "Podcast Info").
But for non-default feeds, you get checkboxes which show the override fields.  When you delete the content from the field, it disappears and the checkbox reappears.  (It's a bit hard to explain without trying it, but I'd say it's adequately intuitive).
> Feed overrides

- src/app/dashboard/dashboard.component.spec.ts
- src/app/dashboard/dashboard.component.ts
Needs PRX/cms.prx.org#623.
Related to https://github.com/PRX/id.prx.org/pull/363, but I don't think it needs that to deploy.
If all of a user's shows (accounts) have moved to the new Feeder UI ... show them a modal and redirect them there.
It's always possible that a user will have some shows in Publish and some in Feeder.  That should be fine - this only shows up once all your shows have moved.
> New Feeder UI

- src/app/series/series.component.spec.ts
- src/app/series/series.component.ts
Fixes https://github.com/PRX/id.prx.org/issues/375
Make sure the initial account we assign to a series is one of the authorized `prx:accounts`.  In case your default account has no `plan` in ID.
> Fix series default account

- src/app/shared/model/distribution.model.spec.ts
- src/app/shared/model/distribution.model.ts
Part of [Feeder migration to remove beta links](https://github.com/PRX/feeder.prx.org/issues/825)
> Remove default podcast link

- src/app/shared/model/story.model.ts
Validate the HTML-encoded description bytes is < 4000.
The flow goes like this:
1. User enters a description markdown of something like 3000 chars.  Frontend validations are fine with that.
2. User clicks save - CMS saves the markdown plus the HTML encoded version to the database.
3. After save, we decode the `description` field from the API (the HTML-encoded one)... calculate byte length, and highlight the field in red with the text "Description is too long"
4. Since this is a strict validation, user is prevented from publishing the episode until they fix the problem.
> Validate description bytes

- src/app/shared/model/story.model.ts
My previous PR marked the description invalid when > 4000 bytes, but didn't allow you to edit and resave it.
This one does, by detecting that you've altered the Description Markdown.
Also tells you the number of characters too long you are.
And excludes some series that don't use Apple delegated delivery.
> Allow editing description and re-saving; exclude some series
